### PR TITLE
r1 00 q3 but better

### PR DESCRIPTION
**Pull request by RedMincrafter**
but also i finally made a python
pls work

### CODE REVIEW

**Comment by RedMincrafter** [comment]
mm im trying cli git and it is weird,

**Comment by macaquedev** [comment]
Throughout, you are missing a lot of latex. EVERY single number should have dollar signs around it. Also please note that the singular of dice is *die*, and not dice!!

**Review by myst-6 — DISMISSED** [review]
^

**Comment by macaquedev** [comment]
@RedMincrafter 
image

can you please stop wasting our time with nonsense PRs, and actually test your code for once? I'm sure all the rest of us would appreciate it, thanks!

**Review by macaquedev — CHANGES_REQUESTED** [review]
^

**Comment by macaquedev** [comment]
image
LOLLLLL

**Comment by macaquedev** [comment]
use <SCode>itertools.stuff idk</SCode> not ```

**Comment by macaquedev** [comment]
"at least one of the second pair has a value of less than or equal to 8"
should be
"at least one of the second pair has a value less than or equal to 8"

**Comment by macaquedev** [comment]
"Given the first two dice, you can generate every single combination, in a set."

Fix punctuation please!!

**Comment by macaquedev** [comment]
image

missing latex...

**Review by macaquedev — APPROVED** [review]
good well done

**Pull request merged**
