### PR TITLE
Sorting and Searching

### PR DESCRIPTION
**Pull request by myst-6**
1. Added a sorting feature. You can sort by year, difficulty, or title in ascending or descending order.
2. Added a searching feature. You can search by title.
3. Changed the filter icon to some tags. Let me know if you like this or the old icon better.

### CODE REVIEW

**Comment by macaquedev** [comment]
Everything else is perfect, and the filter is good.

**Comment by ykr5184** [comment]
If you search for something, it only appears if it is allowed to by the current tag selection, but I would assume that when you search it should appear even if you deselected its tags. Basically, I think the searching should be separate from the tags system.

**Comment by macaquedev** [comment]
good point @ykr5184, I didn't actually notice this

**Comment by vladimirfilip** [comment]
Everything is great, though I preferred the previous filter icon; IMO it is clearer to see at first glance that a funnel icon corresponds to filtering than a tag icon.

**Comment by myst-6** [comment]
> just have "Year","Difficulty","Title", and then a "descending" toggle on top. That will be a ton cleaner IMO

I've done this now.

> I preferred the previous filter icon; IMO it is clearer to see at first glance that a funnel icon corresponds to filtering than a tag icon.

Actually, I agree, and I've reverted the change.

> I think the searching should be separate from the tags system.

Now, whenever you have a non-empty search criterion, it ignores your filters. What do you think about that? @ykr5184

**Review by macaquedev — APPROVED** [review]
Good work @myst-6 !!

**Pull request merged**
