### PR TITLE
Responsive layout

### LINKED ISSUE #46: Mobile Layout
The website does not render well in portrait.

### PR DESCRIPTION
**Pull request by myst-6**
I think the website works well in portrait mode now...

That was easier than I thought it'd be, lol

So, since I haven't suffered enough, let me know if the layout should change differently anywhere.

Closes #46 as well.

### CODE REVIEW

**Comment by vladimirfilip** [comment]
I've tested on phone and tablet. On tablet, the layout is perfect out-of-the-box, but on phone the layout only works when desktop site is enabled. Is there a way to force desktop site mode from the front-end? Maybe through a meta viewport tag?

**Comment by myst-6** [comment]
How does it look now @vladimirfilip ?

**Comment by myst-6** [comment]
It seems to work on my phone

**Comment by vladimirfilip** [comment]
Beautiful

**Review by vladimirfilip — APPROVED** [review]

**Pull request merged**
