### PR TITLE
Blockchains

### PR DESCRIPTION
**Pull request by macaquedev**
second time lucky, @JuliaTatad

### CODE REVIEW

**Comment by macaquedev** [comment]
I think some hideous merge conflicts happened, I'm just cleaning up the mess. @myst-6 please disregard the previous commit.

**Comment by macaquedev** [comment]
17000th time lucky maybe? @myst-6, please try reviewing now.

**Comment by macaquedev** [comment]
@JuliaTatad there is no way that block-chains is a "hard" problem. Please reconsider. @myst-6 feel free to edit

**Review by myst-6 — APPROVED** [review]
yahoo

**Comment by myst-6** [comment]
@AG-88301 please could you accept (and/or double-check) this, I made the last commit so it won't let me merge it.

**Review by AG-88301 — APPROVED** [review]
Preview looks good

**Pull request merged**
