### PR TITLE
Bio1 judge

### PR DESCRIPTION
**Pull request by macaquedev**

### CODE REVIEW

**Comment by myst-6** [comment]
I think it's good apart from one thing. There's no gap between the label of a button and the button itself, which looks weird IMO.
image

**Comment by myst-6** [comment]
Also, I'll need to fix up the code to make the quality better. I looked at one file and saw `: any` so yeah 🤣

**Review by myst-6 — CHANGES_REQUESTED** [review]
^

**Comment by macaquedev** [comment]
oh noooo not vercel..

**Comment by macaquedev** [comment]
issue - SRunner component doesn't allow switching between problems....
@myst-6 can you fix this?

**Comment by myst-6** [comment]
e

**Comment by myst-6** [comment]
test

**Review by myst-6 — DISMISSED** [review]

**Review by myst-6 — APPROVED** [review]

**Comment by myst-6** [comment]
@vladimirfilip have fun reviewing it
you probably don't need to review the code since there's so much, just review the functionality 😄 
if you'd like to review the code then go ahead though!

**Review by vladimirfilip — CHANGES_REQUESTED** [review]
First of all, orz
There are only a couple quality-of-life issues that I found:
- When viewing the details of a CE verdict for a C++ submission, there seems to be a string encoding issue when displaying the checker output. For example, when I submitted the line `for (i = 0; i <= 1e9; i++)` without defining `i`, I get the following checker output:
image
- When writing a solution in one language, and then switching to another language, the code editor contents are not cleared or saved. It would be nice if the editor could save the user's solutions in localStorage, and allow users to have multiple solutions in different languages for a single problem.

**Review by vladimirfilip — APPROVED** [review]
orz

**Pull request merged**
