### PR TITLE
Bio1 2003 q3

### PR DESCRIPTION
**Pull request by AG-88301**

### CODE REVIEW

**Review by macaquedev — CHANGES_REQUESTED** [review]
Codeblock is wrong. Explanation is not good enough

**Comment by macaquedev** [comment]
isn't your "combs" function mathematically equivalent to nCr? LOL

**Review by macaquedev — CHANGES_REQUESTED** [review]
still some work to be done ^

**Comment by AG-88301** [comment]
> isn't your "combs" function mathematically equivalent to nCr? LOL

idk 😭

**Comment by macaquedev** [comment]
image

this is the recursive definition of nCr... haven't you literally just reinvented nCr in your code? @AG-88301

**Review by macaquedev — APPROVED** [review]
as it is now is fine

**Pull request merged**
