### PR TITLE
Filtering, and more

### PR DESCRIPTION
**Pull request by myst-6**
You can now:

- Adjust the width of the problem list or problem viewer
- Collapse the problem list or problem viewer
- Filter on year or tag

I'll add sorting into a different branch, I think this PR is already long enough...

### CODE REVIEW

**Comment by myst-6** [comment]
I just found a bug that the menu gets obscured when no problems are found, I'll try this fix asap

**Comment by myst-6** [comment]
Fixed

**Comment by macaquedev** [comment]
@myst-6 can you add filter by difficulty?

**Comment by macaquedev** [comment]
To add to @vladimirfilip's comments, @myst-6 , I think the tags should be sorted in alphabetical order not by order of number of problems with each tag. Because at the moment we have Q1, Q3 then Q2 😆

**Comment by myst-6** [comment]
I've added the filter by difficulty, and I've sorted the tags in lexicographical order.

> Beautiful, the level of polish is amazing.
> 
> Just a few points:
> 
> * To re-iterate what @macaquedev suggested, filtering by difficulty would be nice.
> * Hovering over the bar between the two panels causes the cursor to turn white.
> * There's quite a bit of flickering when the problem viewer panel is collapsed.
> * Problemset component is wider in the BIO1 page than the BIO2 page

For some reason, I can't reproduce any of the last three issues. Could you send a screenshot or something? Or, if you think it's an easy fix then it would be nice for you to do that. If there's flickering, you could go to the line with the comment about flickering and increase the value from $2$ to like $4$ or $8$ perhaps?

**Comment by macaquedev** [comment]
I cannot reproduce any of the issues, and @myst-6 your last commit is perfect.

**Comment by vladimirfilip** [comment]
I looked into the last 3 points:

* **Hovering over the bar between the two panels causes the cursor to turn white.**
I couldn't find anything in the code that causes this. The white cursor only lasts momentarily before returning to a visible `col-resize` cursor, so it's probably just a Chakra UI rendering issue.
* **There's quite a bit of flickering when the problem viewer panel is collapsed.**
Changing the constant from $2$ to $8$ significantly decreased flickering. 
* **Problemset component is wider in the BIO1 page than the BIO2 page**
This only showed up on my machine because I use a 21:9 monitor. The issue itself was caused by the longer About section in the Round 1 page. I considered fixing this by setting `maxWidth` to a constant pixel value, but that would mess with resizing so I left it alone.

These issues were fairly minor so I'm fine if the branch is merged as-is.

**Review by vladimirfilip — APPROVED** [review]

**Review by macaquedev — APPROVED** [review]

**Pull request merged**
