### PR TITLE
separated people based on role

### PR DESCRIPTION
**Pull request by AG-88301**
people now sorted based on roles
image

People names in alphabetical order instead of random

# TO BE REVIEWED BY DEVS ONLY 
(other opinions are welcome)

### CODE REVIEW

**Comment by ykr5184** [comment]
It looks fine, but perhaps Boris should be first overriding the alphabetical system, as he is the creator, and also has all three tags.

**Review by vladimirfilip — CHANGES_REQUESTED** [review]
I agree with @ykr5184

**Comment by vladimirfilip** [comment]
A founder tag could also work.

**Comment by AG-88301** [comment]
Could also do it alphabetical by surname and hall would be before Pylypenko

**Review by vladimirfilip — APPROVED** [review]
💯

**Pull request merged**
